# Generated by Django 5.0.6 on 2025-06-25 16:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0004_comentarios'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentarios',
            options={'ordering': ['-created'], 'verbose_name': 'Comentario', 'verbose_name_plural': 'Comentarios'},
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='coment',
            field=ckeditor.fields.RichTextField(verbose_name='Comentario'),
        ),
    ]
